---
fail_fast: false
repos:
  - repo: meta
    hooks:
      - id: check-hooks-apply
      - id: check-useless-excludes
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v6.0.0"
    hooks:
      - id: check-case-conflict
      - id: check-json
      - id: check-merge-conflict
      - id: check-yaml
      - id: trailing-whitespace
        # allow it in external dependencies and test references
        exclude: |
          (?x)(
              src/sst/core/libltdl/|
              external/|
              tests/refFiles/
          )
  - repo: https://github.com/cheshirekow/cmake-format-precommit
    rev: "v0.6.13"
    hooks:
      - id: cmake-format
        args: [--config-files, experimental/.cmake-format.yaml, --in-place]
        additional_dependencies:
          - pyyaml
      - id: cmake-lint
        additional_dependencies:
          - pyyaml
  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: "v20.1.8"
    hooks:
      - id: clang-format
        types_or: [c++, c]
        exclude: |
          (?x)(
              build/|
              src/sst/core/libltdl/|
              external/
          )
  # - repo: https://github.com/shellcheck-py/shellcheck-py
  #   rev: v0.10.0.1
  #   hooks:
  #     - id: shellcheck
  #       exclude: |
  #         (?x)(
  #             autogen.sh|
  #             scripts/clang-format-test.sh|
  #             scripts/cmake-format-test.sh
  #         )
  - repo: https://github.com/rhysd/actionlint
    rev: "v1.7.12"
    hooks:
      - id: actionlint
        additional_dependencies:
          - "github.com/wasilibs/go-shellcheck/cmd/shellcheck@v0.11.1"
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: "v0.14.2"
    hooks:
      - id: ruff-check
  - repo: https://github.com/pre-commit/mirrors-mypy
    # This needs to match the last version that still supports the minimum
    # required Python version
    rev: "v1.19.1"
    hooks:
      - id: mypy
        additional_dependencies:
          - blessings
          - testtools
          - types-Pygments
        # Work around config file setting exclusion rules being bypassed when
        # filenames are explicitly passed on the command line.  See
        # https://github.com/python/mypy/pull/12373#issuecomment-1071662559
        # for the idea.
        args: [.]
        pass_filenames: false
  - repo: https://github.com/zizmorcore/zizmor-pre-commit
    rev: v1.16.0
    hooks:
      - id: zizmor
        args: [--no-progress, --persona=pedantic, --fix=all]
  - repo: https://github.com/renovatebot/pre-commit-hooks
    rev: 41.163.7
    hooks:
      - id: renovate-config-validator
        args: [--strict]
