---
name: rocky9

on:
  workflow_call:

concurrency:
  group: at2-rocky9-${{github.workflow}}-${{github.ref}}-${{github.event.pull_request.number || github.run_number}}
  cancel-in-progress: true

permissions: {}

jobs:
  rocky9:
    name: Build/test core ref and elements devel
    runs-on:
      - self-hosted
      - sst-rocky9
    steps:

      - name: Clone core
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          path: sst-core
          persist-credentials: false

      - name: Clone elements
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          path: sst-elements
          persist-credentials: false
          ref: devel
          repository: sstsimulator-at2/sst-elements

      # There is no need to install additional system-level depdendencies, as
      # they are all already in the image.

      - name: Install and configure ccache
        uses: hendrikmuhs/ccache-action@d62db5f07c26379fc4b4e0916f098a92573c3b03  # v1.2.23
        with:
          append-timestamp: false
          create-symlink: false
          key: >-
            ccache-${{ github.job }}
          max-size: "2GB"
          verbose: 2

      - name: Set environment variables
        run: |
          MAKEFLAGS="-j4"
          echo "MAKEFLAGS=${MAKEFLAGS}" >> "${GITHUB_ENV}"
          echo "TERM=dumb" >> "${GITHUB_ENV}"

      - name: Compile core
        run: |
          # TODO the argument does nothing as long as Spack is unavailable
          sst-core/.github/scripts/core_autotools_noflags_nodeps.sh gcc

      - name: Test core
        run: |
          install_autotools_noflags_nodeps_gcc/bin/sst-test-core

      - name: Compile elements
        run: |
          # TODO the argument does nothing as long as Spack is unavailable
          sst-core/.github/scripts/elements_autotools_noflags_nodeps.sh gcc

      - name: Test elements
        run: |
          install_autotools_noflags_nodeps_gcc/bin/sst-test-elements
