---
name: rocky9

on:
  workflow_call:

permissions: {}

jobs:
  rocky9:
    runs-on: ubuntu-24.04
    container:
      image: rockylinux@sha256:197b1569a8e5d46de75412cfd80b88a437d25bb2a5338dc82d5421d835245ec7
    steps:
      - name: stub
        run: |
          echo "with mpi"
