---
name: rocky9

on:
  workflow_call:

permissions: {}

jobs:
  rocky9:
    runs-on:
      - self-hosted
      - sst-rocky9
    steps:
      - name: ccache
        uses: hendrikmuhs/ccache-action@63069e3931dedbf3b63792097479563182fe70d1  # v1.2
        with:
          append-timestamp: false
          create-symlink: true
          key: >-
            ccache-${{ github.job }}
          max-size: "2GB"
          verbose: 2
      - name: stub
        run: |
          echo "with mpi"
