---
name: AT2

# yamllint disable-line rule:truthy
on:
  workflow_call:

permissions: {}

# Cancels any in progress 'workflow' associated with this PR
concurrency:
  group: build_and_test_at2-${{github.workflow}}-${{github.ref}}-${{github.event.pull_request.number || github.run_number}}
  cancel-in-progress: true

jobs:
  # Jobs depend on the output of pre-checks to run.
  # Cancels new workflows if prior runs were successful (same tree hash)
  pre-checks:
    name: Determine if build/test should be performed
    runs-on: ubuntu-24.04
    permissions:
      actions: write # needed by skip-duplicate-actions
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
    steps:
      - id: skip_check
        uses: fkirc/skip-duplicate-actions@f75f66ce1886f00957d99748a42c724f4330bdcf # v5.3.1
        with:
          skip_after_successful_duplicate: 'true'
  # rocky8:
  #   needs: pre-checks
  #   if: ${{ needs.pre-checks.outputs.should_skip != 'true' && (github.event.action == 'synchronize' || github.event.action == 'opened') || github.event.action == 'labeled' }}
  #   uses:
  #     ./.github/workflows/at2-rocky8.yml
  rocky8-nompi:
    needs: pre-checks
    if: ${{ needs.pre-checks.outputs.should_skip != 'true' && (github.event.action == 'synchronize' || github.event.action == 'opened') || github.event.action == 'labeled' }}
    uses:
      ./.github/workflows/at2-rocky8-nompi.yml
  # rocky9:
  #   needs: pre-checks
  #   if: ${{ needs.pre-checks.outputs.should_skip != 'true' && (github.event.action == 'synchronize' || github.event.action == 'opened') || github.event.action == 'labeled' }}
  #   uses:
  #     ./.github/workflows/at2-rocky9.yml
  rocky9-nompi:
    needs: pre-checks
    if: ${{ needs.pre-checks.outputs.should_skip != 'true' && (github.event.action == 'synchronize' || github.event.action == 'opened') || github.event.action == 'labeled' }}
    uses:
      ./.github/workflows/at2-rocky9-nompi.yml
  # rocky9-cmake:
  #   needs: pre-checks
  #   if: ${{ needs.pre-checks.outputs.should_skip != 'true' && (github.event.action == 'synchronize' || github.event.action == 'opened') || github.event.action == 'labeled' }}
  #   uses:
  #     ./.github/workflows/at2-rocky9-cmake.yml
  # rocky9-clang:
  #   needs: pre-checks
  #   if: ${{ needs.pre-checks.outputs.should_skip != 'true' && (github.event.action == 'synchronize' || github.event.action == 'opened') || github.event.action == 'labeled' }}
  #   uses:
  #     ./.github/workflows/at2-rocky9-clang.yml
  # rocky9-make-dist:
  #   needs: pre-checks
  #   if: ${{ needs.pre-checks.outputs.should_skip != 'true' && (github.event.action == 'synchronize' || github.event.action == 'opened') || github.event.action == 'labeled' }}
  #   uses:
  #     ./.github/workflows/at2-rocky9-make-dist.yml
  # rocky9-mr-2:
  #   needs: pre-checks
  #   if: ${{ needs.pre-checks.outputs.should_skip != 'true' && (github.event.action == 'synchronize' || github.event.action == 'opened') || github.event.action == 'labeled' }}
  #   uses:
  #     ./.github/workflows/at2-rocky9-mr-2.yml
  # rocky9-mt-2:
  #   needs: pre-checks
  #   if: ${{ needs.pre-checks.outputs.should_skip != 'true' && (github.event.action == 'synchronize' || github.event.action == 'opened') || github.event.action == 'labeled' }}
  #   uses:
  #     ./.github/workflows/at2-rocky9-mt-2.yml
  # ubuntu2204:
  #   needs: pre-checks
  #   if: ${{ needs.pre-checks.outputs.should_skip != 'true' && (github.event.action == 'synchronize' || github.event.action == 'opened') || github.event.action == 'labeled' }}
  #   uses:
  #     ./.github/workflows/at2-ubuntu2204.yml
  ubuntu2404-nompi:
    needs: pre-checks
    if: ${{ needs.pre-checks.outputs.should_skip != 'true' && (github.event.action == 'synchronize' || github.event.action == 'opened') || github.event.action == 'labeled' }}
    uses:
      ./.github/workflows/at2-ubuntu2404-nompi.yml
  # ubuntu2404:
  #   needs: pre-checks
  #   if: ${{ needs.pre-checks.outputs.should_skip != 'true' && (github.event.action == 'synchronize' || github.event.action == 'opened') || github.event.action == 'labeled' }}
  #   uses:
  #     ./.github/workflows/at2-ubuntu2404.yml
