---
name: pre-commit

# yamllint disable-line rule:truthy
on:
  workflow_call:

concurrency:
  group: style-${{github.ref}}-${{github.event.pull_request.number || github.run_number}}
  cancel-in-progress: true

permissions: {}

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    # for label manipulation
    permissions:
      issues: write
      pull-requests: write
    strategy:
      fail-fast: false
    steps:
      # Set the WIP label immediately before testing
      - name: SET WIP Label before testing
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
              github.rest.issues.addLabels({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                labels: ['AT: WIP']
              })
        if: github.event_name == 'pull_request'

      # Get this user's SST-core repo/branch
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
          # ref: ${{ github.event.pull_request.head.sha }}
      # Run all the pre-commit checks: clang-format, cmake-format, ...
      - uses: actions/setup-python@v5
      - uses: pre-commit/action@2c7b3805fd2a0fd8c1884dcaebf91fc102a13ecd # v3.0.1

      #############################################
      # LABEL RESULTS - USING actions/github-script
      #############################################

      # Label the Results - FOR FAILURE
      - name: ADD FAIL + WIP Label Results for Failure
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
              github.rest.issues.addLabels({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                labels: ['AT: CLANG-FORMAT FAIL', 'AT: WIP']
              })
        if: ${{ failure() && github.event_name == 'pull_request' }}

      - name: REMOVE PASS Label Results for Failure
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
              github.rest.issues.removeLabel({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                name: 'AT: CLANG-FORMAT PASS'
              })
        if: ${{ failure() && github.event_name == 'pull_request' }}
        continue-on-error: true

      - name: ADD COMMENT ABOUT FAIL
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
              github.rest.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: '**PRE-COMMIT - FAILED** (on last commit): <br>Run `pre-commit run -a` locally to view fixes'
              })
        if: ${{ failure() && github.event_name == 'pull_request' }}


      #############################

      # Label the Results - FOR SUCCESS
      - name: ADD PASS Label Results for Success
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
              github.rest.issues.addLabels({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                labels: ['AT: CLANG-FORMAT PASS']
              })
        if: ${{ success() && github.event_name == 'pull_request' }}

      - name: REMOVE WIP Label Results for Success
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
              github.rest.issues.removeLabel({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                name: 'AT: WIP'
              })
        if: ${{ success() && github.event_name == 'pull_request' }}
        continue-on-error: true

      - name: REMOVE FAIL Label Results for Success
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
              github.rest.issues.removeLabel({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                name: 'AT: CLANG-FORMAT FAIL'
              })
        if: ${{ success() && github.event_name == 'pull_request' }}
        continue-on-error: true

      - name: ADD COMMENT ABOUT SUCCESS
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
              github.rest.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: '**PRE-COMMIT - PASSED**'
              })
        if: ${{ success() && github.event_name == 'pull_request' }}
